version: "3"
services:
  react-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: "react-app-test"
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: "react-web-app"
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
