name: Deploy Frontend
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest # the OS your job should run on
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t sanyamgupta/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true sanyamgupta/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: react-docker-demo
          environment_name: react-docker-demo-env
          version_label: ${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-us-east-1-730335255488
          region: us-east-1
          deployment_package: deploy.zip

      - name: Deployed!
        run: echo App deployed to ELB
